In [99]:
from datetime import date
import pandas as pd
import numpy as np
from graphit_base import run_graphs, do_bar_graph_by_day, get_data
pd.set_option('display.max_rows', None)

In [13]:
START = date(2019, 5, 10)
END = date(2019, 8, 12)
VCLASSES = ("pedestrian", "cyclist", "motorbike", "car",
            "taxi", "van", "minibus", "bus", "rigid",
            "truck", "emergency car", "emergency van",
            "fire engine")

In [14]:
df = pd.DataFrame(get_data('13079', 'in', START, END))
df.columns = ('Date',) + VCLASSES
df.index = pd.to_datetime(df['Date'])

In [15]:
df.head()

,Date,pedestrian,cyclist,motorbike,car,taxi,van,minibus,bus,rigid,truck,emergency car,emergency van,fire engine
Date,,,,,,,,,,,,,,
2019-05-10 00:00:00,2019-05-10T00:00:00+00:00,0,0,0,8,0,1,0,0,0,0,0,0,0
2019-05-10 00:05:00,2019-05-10T00:05:00+00:00,0,1,0,7,0,0,0,0,0,0,0,0,0
2019-05-10 00:10:00,2019-05-10T00:10:00+00:00,0,0,0,16,0,0,0,0,1,0,0,0,0
2019-05-10 00:15:00,2019-05-10T00:15:00+00:00,1,0,0,9,0,1,0,0,0,0,0,0,0
2019-05-10 00:20:00,2019-05-10T00:20:00+00:00,0,0,0,11,0,0,0,0,2,1,0,0,0

In [16]:
df = df.resample('D').sum()

In [17]:
df.head()

,pedestrian,cyclist,motorbike,car,taxi,van,minibus,bus,rigid,truck,emergency car,emergency van,fire engine
Date,,,,,,,,,,,,,
2019-05-10,725,815,207,7915,17,1050,22,205,173,45,5,13,0
2019-05-11,717,538,148,8210,14,584,16,179,45,5,6,8,0
2019-05-12,622,657,136,6923,10,384,11,87,23,8,6,6,0
2019-05-13,696,851,169,7885,7,1224,19,232,175,40,2,10,0
2019-05-14,659,849,199,7925,6,1235,21,226,176,58,4,4,0

In [18]:
df.pedestrian[:'2019-06-30'].mean()

706.6538461538462

In [19]:
df.pedestrian['2019-07-01':'2019-07-24'].mean()

727.9583333333334

In [21]:
df.pedestrian['2019-07-25':].mean()

691.2222222222222

In [22]:
df['ave'] = 0

In [35]:
df.loc[:'2019-06-30'].ave = df['pedestrian'][:'2019-06-30'].mean()
df.loc['2019-07-01':'2019-07-24'].ave = df.pedestrian['2019-07-01':'2019-07-24'].mean()
df.loc['2019-07-25':].ave = df.pedestrian['2019-07-25':].mean()

In [34]:
df

,pedestrian,cyclist,motorbike,car,taxi,van,minibus,bus,rigid,truck,emergency car,emergency van,fire engine,ave
Date,,,,,,,,,,,,,,
2019-05-10,725,815,207,7915,17,1050,22,205,173,45,5,13,0,706.653846
2019-05-11,717,538,148,8210,14,584,16,179,45,5,6,8,0,706.653846
2019-05-12,622,657,136,6923,10,384,11,87,23,8,6,6,0,706.653846
2019-05-13,696,851,169,7885,7,1224,19,232,175,40,2,10,0,706.653846
2019-05-14,659,849,199,7925,6,1235,21,226,176,58,4,4,0,706.653846
2019-05-15,686,1043,175,8285,5,1228,28,240,164,55,9,8,0,706.653846
2019-05-16,776,959,251,8088,11,1254,25,224,185,70,2,3,0,706.653846
2019-05-17,823,1060,240,8593,21,1274,27,238,179,58,11,16,0,706.653846
2019-05-18,711,573,182,8359,25,597,20,176,45,5,5,9,0,706.653846
2019-05-19,658,658,155,6918,13,370,13,80,29,6,5,4,0,706.653846
2019-05-20,798,1145,232,7938,11,1226,25,255,205,53,6,5,0,706.653846
2019-05-21,610,925,212,7342,14,1091,29,206,180,65,3,8,0,706.653846
2019-05-22,731,1099,260,8548,25,1282,31,238,210,49,3,9,0,706.653846
2019-05-23,817,1059,251,8504,24,1304,26,220,234,74,4,9,0,706.653846
2019-05-24,731,934,252,8290,26,1188,33,223,177,55,6,13,0,706.653846
2019-05-25,760,656,208,7709,27,562,12,182,37,11,2,9,0,706.653846
2019-05-26,639,647,373,6639,30,363,18,89,16,3,9,9,0,706.653846
2019-05-27,596,564,179,6286,20,415,6,85,37,10,2,9,0,706.653846
2019-05-28,675,1002,184,7591,16,1222,25,225,208,71,3,7,0,706.653846
2019-05-29,671,1034,212,7751,26,1213,22,220,191,40,4,12,0,706.653846
2019-05-30,717,914,249,8233,27,1154,21,231,201,78,5,4,0,706.653846
2019-05-31,642,848,219,8563,27,1251,20,233,201,88,8,5,0,706.653846
2019-06-01,655,791,206,8401,28,595,30,176,63,18,6,4,0,706.653846
2019-06-02,660,720,159,6872,18,404,12,88,30,10,9,13,0,706.653846
2019-06-03,775,1056,204,8012,20,1215,24,230,223,49,0,9,0,706.653846
2019-06-04,725,1116,209,8367,15,1312,34,232,222,49,3,17,0,706.653846
2019-06-05,753,1049,231,8264,14,1266,30,234,242,93,5,3,0,706.653846
2019-06-06,734,1022,208,8492,18,1291,27,222,240,67,9,10,0,706.653846
2019-06-07,742,1044,215,8763,36,1179,27,224,260,95,7,11,0,706.653846
2019-06-08,775,523,156,8342,20,578,17,178,58,19,9,13,0,706.653846
2019-06-09,632,722,166,6894,29,369,13,79,16,15,7,9,0,706.653846
2019-06-10,708,797,191,8019,30,1162,23,216,193,47,6,13,0,706.653846
2019-06-11,746,1047,200,8029,24,1235,35,224,211,36,9,12,0,706.653846
2019-06-12,776,1124,210,8068,21,1228,35,224,193,35,6,11,0,706.653846
2019-06-13,785,884,175,8373,20,1193,35,230,209,78,6,14,0,706.653846
2019-06-14,871,1016,222,8463,14,1184,28,239,201,64,8,11,0,706.653846
2019-06-15,697,722,195,8159,15,600,14,190,39,8,5,6,0,706.653846
2019-06-16,596,657,173,6985,17,421,19,81,17,8,4,7,0,706.653846
2019-06-17,726,1041,221,7906,13,1227,24,226,225,57,7,11,0,706.653846
2019-06-18,679,1057,214,7993,25,1215,42,231,247,60,9,9,0,706.653846
2019-06-19,654,1070,206,8279,14,1269,31,234,274,82,10,12,0,706.653846
2019-06-20,711,958,219,7843,13,1218,33,224,256,71,6,10,0,706.653846
2019-06-21,749,1019,262,8065,19,1230,18,225,220,72,6,7,0,706.653846
2019-06-22,763,800,204,8257,30,614,14,174,48,13,11,8,0,706.653846
2019-06-23,662,736,167,6748,21,432,11,84,29,10,4,4,0,706.653846
2019-06-24,689,1119,230,7847,9,1279,33,240,210,55,8,7,0,706.653846
2019-06-25,763,1007,234,8523,17,1304,30,233,310,117,11,16,0,706.653846
2019-06-26,716,1198,251,8351,24,1299,35,247,307,106,8,13,0,706.653846
2019-06-27,676,996,226,8778,12,1334,23,232,230,78,2,12,0,706.653846
2019-06-28,709,970,265,8280,19,1219,37,233,258,70,7,10,0,706.653846
2019-06-29,624,689,175,8370,27,633,15,202,51,15,11,11,0,706.653846
2019-06-30,535,740,208,7273,21,438,22,82,23,15,5,5,0,706.653846
2019-07-01,723,1080,225,7751,19,1235,35,234,230,58,3,8,0,727.958333
2019-07-02,651,1036,214,7865,19,1294,29,232,261,77,4,10,0,727.958333
2019-07-03,700,1115,223,8270,21,1284,38,246,241,96,4,3,0,727.958333
2019-07-04,625,993,212,8379,14,1284,32,237,219,82,8,6,0,727.958333
2019-07-05,631,987,271,7942,63,1130,72,213,225,47,9,13,0,727.958333
2019-07-06,695,706,216,8029,42,571,48,208,52,10,17,13,0,727.958333
2019-07-07,633,769,208,7368,41,420,52,92,27,5,9,6,0,727.958333
2019-07-08,717,1235,238,7735,15,1236,47,239,202,70,7,8,0,727.958333
2019-07-09,825,1274,231,8240,33,1320,56,243,260,68,9,8,0,727.958333
2019-07-10,818,1299,269,8376,27,1277,62,236,310,115,15,10,0,727.958333
2019-07-11,718,1192,215,8520,26,1333,63,248,276,79,7,8,0,727.958333
2019-07-12,737,1092,234,8606,23,1234,66,240,267,74,11,11,0,727.958333
2019-07-13,789,752,200,7899,33,576,52,217,66,12,16,8,0,727.958333
2019-07-14,630,758,192,6758,35,372,33,91,26,2,10,10,0,727.958333
2019-07-15,786,1292,240,7599,35,1189,56,223,196,38,15,15,0,727.958333
2019-07-16,793,1300,237,7727,38,1211,35,221,197,36,6,7,0,727.958333
2019-07-17,796,1292,267,7840,44,1181,50,246,247,59,12,6,0,727.958333
2019-07-18,813,1230,246,8025,38,1213,51,234,192,36,13,5,0,727.958333
2019-07-19,804,1061,188,8104,28,1137,47,240,181,33,14,9,0,727.958333
2019-07-20,727,743,160,7935,37,508,38,207,42,8,9,10,0,727.958333
2019-07-21,745,845,168,6621,41,379,38,99,21,7,7,9,0,727.958333
2019-07-22,710,1139,217,8030,49,1202,65,232,238,57,14,13,0,727.958333
2019-07-23,759,1140,206,8305,49,1309,44,236,281,68,7,9,0,727.958333
2019-07-24,646,1040,214,8453,55,1226,53,241,266,52,7,7,0,727.958333
2019-07-25,604,912,191,8635,44,1265,56,242,294,69,9,7,0,691.222222
2019-07-26,695,983,228,8569,29,1196,37,226,283,85,7,6,0,691.222222
2019-07-27,665,512,146,8182,21,591,42,217,66,14,8,10,0,691.222222
2019-07-28,613,525,126,6893,32,390,42,107,19,7,8,9,0,691.222222
2019-07-29,684,1058,212,7405,25,1186,38,213,211,41,7,6,0,691.222222
2019-07-30,725,998,153,7662,16,1196,60,223,224,46,16,13,0,691.222222
2019-07-31,776,1112,223,7824,25,1277,56,238,248,67,6,4,0,691.222222
2019-08-01,772,1018,231,7839,24,1223,38,236,179,24,8,7,0,691.222222
2019-08-02,749,1031,242,7851,34,1205,39,228,202,49,6,12,0,691.222222
2019-08-03,715,764,186,7411,47,543,37,194,43,8,8,5,0,691.222222
2019-08-04,682,696,187,6295,44,389,37,96,19,7,5,5,0,691.222222
2019-08-05,688,1047,206,7361,23,1216,50,223,220,45,13,8,0,691.222222
2019-08-06,676,1033,179,7733,36,1225,50,218,186,37,12,8,0,691.222222
2019-08-07,759,1047,229,7561,43,1218,49,217,224,59,10,9,0,691.222222
2019-08-08,654,1052,214,7457,27,1154,42,215,214,31,15,9,0,691.222222
2019-08-09,752,893,189,8020,34,1095,51,222,180,32,9,8,0,691.222222
2019-08-10,706,509,150,7420,35,558,47,192,48,11,10,14,0,691.222222
2019-08-11,527,576,104,6474,25,388,46,86,22,6,9,9,0,691.222222

In [103]:
df2 = pd.DataFrame(index=df.index)

In [104]:
df2['ave'] = np.NaN

In [106]:
df2.loc[:'2019-06-30'].ave = df['pedestrian'][:'2019-06-30'].mean()
df2.loc['2019-07-01':'2019-07-24'].ave = df.pedestrian['2019-07-01':'2019-07-24'].mean()
df2.loc['2019-07-25':].ave = df.pedestrian['2019-07-25':].mean()

In [107]:
df2

                   ave
Date
2019-05-10  706.653846
2019-05-11  706.653846
2019-05-12  706.653846
2019-05-13  706.653846
2019-05-14  706.653846
2019-05-15  706.653846
2019-05-16  706.653846
2019-05-17  706.653846
2019-05-18  706.653846
2019-05-19  706.653846
2019-05-20  706.653846
2019-05-21  706.653846
2019-05-22  706.653846
2019-05-23  706.653846
2019-05-24  706.653846
2019-05-25  706.653846
2019-05-26  706.653846
2019-05-27  706.653846
2019-05-28  706.653846
2019-05-29  706.653846
2019-05-30  706.653846
2019-05-31  706.653846
2019-06-01  706.653846
2019-06-02  706.653846
2019-06-03  706.653846
2019-06-04  706.653846
2019-06-05  706.653846
2019-06-06  706.653846
2019-06-07  706.653846
2019-06-08  706.653846
2019-06-09  706.653846
2019-06-10  706.653846
2019-06-11  706.653846
2019-06-12  706.653846
2019-06-13  706.653846
2019-06-14  706.653846
2019-06-15  706.653846
2019-06-16  706.653846
2019-06-17  706.653846
2019-06-18  706.653846
2019-06-19  706.653846
2019-06-20  706.653846
2019-06-21  706.653846
2019-06-22  706.653846
2019-06-23  706.653846
2019-06-24  706.653846
2019-06-25  706.653846
2019-06-26  706.653846
2019-06-27  706.653846
2019-06-28  706.653846
2019-06-29  706.653846
2019-06-30  706.653846
2019-07-01  727.958333
2019-07-02  727.958333
2019-07-03  727.958333
2019-07-04  727.958333
2019-07-05  727.958333
2019-07-06  727.958333
2019-07-07  727.958333
2019-07-08  727.958333
2019-07-09  727.958333
2019-07-10  727.958333
2019-07-11  727.958333
2019-07-12  727.958333
2019-07-13  727.958333
2019-07-14  727.958333
2019-07-15  727.958333
2019-07-16  727.958333
2019-07-17  727.958333
2019-07-18  727.958333
2019-07-19  727.958333
2019-07-20  727.958333
2019-07-21  727.958333
2019-07-22  727.958333
2019-07-23  727.958333
2019-07-24  727.958333
2019-07-25  691.222222
2019-07-26  691.222222
2019-07-27  691.222222
2019-07-28  691.222222
2019-07-29  691.222222
2019-07-30  691.222222
2019-07-31  691.222222
2019-08-01  691.222222
2019-08-02  691.222222
2019-08-03  691.222222
2019-08-04  691.222222
2019-08-05  691.222222
2019-08-06  691.222222
2019-08-07  691.222222
2019-08-08  691.222222
2019-08-09  691.222222
2019-08-10  691.222222
2019-08-11  691.222222

In [73]:
df['pedestrian'][:'2019-06-30'].mean()

706.6538461538462