In [4]:
from datetime import date
import pandas as pd
from graphit_base import run_graphs, do_bar_graph, get_data
pd.set_option('display.max_rows', None)

In [9]:
START = date(2019, 5, 10)
END = date(2019, 7, 14)
VCLASSES = ("pedestrian", "cyclist", "motorbike", "car",
            "taxi", "van", "minibus", "bus", "rigid",
            "truck", "emergency car", "emergency van",
            "fire engine")

In [52]:
df = pd.DataFrame(get_data('13079', 'in', START, END))
df.columns = ('Date',) + VCLASSES
df.index = pd.to_datetime(df['Date'])

In [53]:
df.head()

,Date,pedestrian,cyclist,motorbike,car,taxi,van,minibus,bus,rigid,truck,emergency car,emergency van,fire engine
Date,,,,,,,,,,,,,,
2019-05-10 00:00:00,2019-05-10T00:00:00+00:00,0,0,0,8,0,1,0,0,0,0,0,0,0
2019-05-10 00:05:00,2019-05-10T00:05:00+00:00,0,1,0,7,0,0,0,0,0,0,0,0,0
2019-05-10 00:10:00,2019-05-10T00:10:00+00:00,0,0,0,16,0,0,0,0,1,0,0,0,0
2019-05-10 00:15:00,2019-05-10T00:15:00+00:00,1,0,0,9,0,1,0,0,0,0,0,0,0
2019-05-10 00:20:00,2019-05-10T00:20:00+00:00,0,0,0,11,0,0,0,0,2,1,0,0,0

In [54]:
col_list = list(df)
df['total'] = df[col_list].sum(axis=1)

In [55]:
df.head()

,Date,pedestrian,cyclist,motorbike,car,taxi,van,minibus,bus,rigid,truck,emergency car,emergency van,fire engine,total
Date,,,,,,,,,,,,,,,
2019-05-10 00:00:00,2019-05-10T00:00:00+00:00,0,0,0,8,0,1,0,0,0,0,0,0,0,9
2019-05-10 00:05:00,2019-05-10T00:05:00+00:00,0,1,0,7,0,0,0,0,0,0,0,0,0,8
2019-05-10 00:10:00,2019-05-10T00:10:00+00:00,0,0,0,16,0,0,0,0,1,0,0,0,0,17
2019-05-10 00:15:00,2019-05-10T00:15:00+00:00,1,0,0,9,0,1,0,0,0,0,0,0,0,11
2019-05-10 00:20:00,2019-05-10T00:20:00+00:00,0,0,0,11,0,0,0,0,2,1,0,0,0,14

In [56]:
zero_row = df.total == 0
df_zero = df[zero_row]

In [58]:
df_zero.resample('D').count()

,Date,pedestrian,cyclist,motorbike,car,taxi,van,minibus,bus,rigid,truck,emergency car,emergency van,fire engine,total
Date,,,,,,,,,,,,,,,
2019-05-10,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
2019-05-11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-14,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2019-05-15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-16,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2019-05-17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-20,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-05-21,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
2019-05-22,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-05-23,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-05-24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-27,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-05-28,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2019-05-29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-02,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2019-06-03,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-04,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-05,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-06,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-07,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-08,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-11,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-06-12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-13,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-06-14,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-06-15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-17,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2019-06-18,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-06-19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-21,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-06-22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-23,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-06-24,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2019-06-25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-27,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-06-28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-07-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-07-02,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2019-07-03,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-07-04,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2019-07-05,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
2019-07-06,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-07-07,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-07-08,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [60]:
df_zero.between_time('18:00:00', '04:00:00')

,Date,pedestrian,cyclist,motorbike,car,taxi,van,minibus,bus,rigid,truck,emergency car,emergency van,fire engine,total
Date,,,,,,,,,,,,,,,
2019-05-10 18:15:00,2019-05-10T18:15:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-14 03:10:00,2019-05-14T03:10:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-16 00:45:00,2019-05-16T00:45:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-16 01:50:00,2019-05-16T01:50:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-20 02:45:00,2019-05-20T02:45:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-21 00:45:00,2019-05-21T00:45:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-22 01:10:00,2019-05-22T01:10:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-27 01:40:00,2019-05-27T01:40:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-28 01:45:00,2019-05-28T01:45:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-05-28 02:05:00,2019-05-28T02:05:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-02 03:40:00,2019-06-02T03:40:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-11 03:20:00,2019-06-11T03:20:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-13 00:40:00,2019-06-13T00:40:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-14 03:35:00,2019-06-14T03:35:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-17 00:45:00,2019-06-17T00:45:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-17 01:25:00,2019-06-17T01:25:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-17 02:25:00,2019-06-17T02:25:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-18 03:20:00,2019-06-18T03:20:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-21 01:00:00,2019-06-21T01:00:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-24 00:35:00,2019-06-24T00:35:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-24 01:45:00,2019-06-24T01:45:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-24 03:15:00,2019-06-24T03:15:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-06-27 03:55:00,2019-06-27T03:55:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-07-01 01:40:00,2019-07-01T01:40:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-07-03 00:40:00,2019-07-03T00:40:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-07-04 21:45:00,2019-07-04T21:45:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2019-07-08 21:30:00,2019-07-08T21:30:00+00:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0